In [28]:
import pandas as pd
import numpy as np
import json
import re
# import seaborn as sns
import os
import sqlite3

START_YEAR = 2010
END_YEAR = 2021
GROSS_PAY = 'Gross Pay'
REG_PAY = 'Regular Pay'

# id is just the row number PER YEAR, but not super meaningful.
# it is included in the JSON data.
COLUMNS = ['id', 'Year', 'Location', 'First Name', 'Last Name', 'Title', 'Gross Pay', 'Regular Pay', 'Overtime Pay', 'Other Pay']
# LECT_PREFIX = 'LECT-' # Caputes 'LECT-AY', excludes LECT PSOE / LECT SOE

def safe_parse(value):
    # first parse to int, then to float, then return as-is
    try:
        return int(value)
    except:
        try:
            return float(value)
        except:
            return value

DATA_LOADED = {}
def load_data_for_year(year):
    # If not JSON, the decompress the file and load it
    if (not os.path.exists(f"data/json/all-records-{year}.json")) and \
        os.path.exists(f"data/json/all-records-{year}.json.gz"):
        os.system(f"gunzip -k data/json/all-records-{year}.json.gz")
    raw_data = open(f"data/json/all-records-{year}.json").read()
    # Old data via curl has some issues...
    raw_data = raw_data.replace("'", '"') if year < 2022 else raw_data
    raw_data = re.sub(r'[\x00-\x1f\x7f-\x9f]', '', raw_data)
    parsed = json.loads(raw_data)
    # For 2022+ data, I stored only the 'rows' key in the JSON as a list, earlier data is a dict with 'rows' as a key
    if type(parsed) == dict:
        parsed = parsed['rows']
    print(f"Loaded {len(parsed)} records for {year}")
    data = [ [ safe_parse(value) for value in row['cell'] ] for row in parsed ]

    df = pd.DataFrame(data, columns= COLUMNS)
    DATA_LOADED[year] = df
    return df

In [ ]:
# Download Data
!year=2022 && curl "https://ucannualwage.ucop.edu/wage/search.action?_search=false&nd=1631391241333&rows=600000&page=1&sidx=EAW_LST_NAM&sord=asc&year=$year&location=ALL&firstname=&lastname=&title=&startSal=&endSal=" -o "data/json/all-records-$year.json"

:

In [10]:
pd

In [ ]:
# DATA_LOADED[2010] = load_data_for_year(2010)
df2010 = DATA_LOADED[2010]
df2010.head()

Loaded 252540 records for 2010

,id,Year,Location,First Name,Last Name,Title,Gross Pay,Regular Pay,Overtime Pay,Other Pay
0,1,2010,Santa Cruz,*****,*****,ASSISTANT PROFESSOR-ACAD YR,74511.10,69999.96,0.0,4511.14
1,2,2010,Berkeley,***********,***********,GRAD STDNT RES-FULL FEE REM,5369.42,5369.42,0.0,0.00
2,3,2010,Berkeley,***********,***********,TEACHING ASSISTANT - GSHIP,4802.00,4802.00,0.0,0.00
3,4,2010,Berkeley,***********,***********,GRAD STDNT RES- NO REMISSION,3409.01,3409.01,0.0,0.00
4,5,2010,Berkeley,***********,***********,GRAD STDNT RES-FULL FEE REM,11673.90,11673.90,0.0,0.00

In [45]:
def convert_to_csv(year):
    df = load_data_for_year(year)
    # Remove the id column
    df = df.drop(columns=['id'])
    # Save to CSV
    df.to_csv(f"data/csv/all-records-{year}.csv", index=False)
    print(f"Saved data for {year} to CSV")
    return df

def normalize_df_for_db(df):
    # Remove the id column
    df = df.drop(columns=['id'])
    df['Year'] = df['Year'].astype(int)
    # Use SQL-style column names
    df.columns = [col.lower().replace(' ', '_') for col in df.columns]
    # Convert Year to int
    return df

In [ ]:
def load_sqlite_db(conn, start_year=2010, end_year=2023  ):
    # Create table
    conn.cursor().execute('''CREATE TABLE IF NOT EXISTS salaries
                 (id INTEGER PRIMARY KEY, year INTEGER, location TEXT, first_name TEXT, last_name TEXT, title TEXT, gross_pay REAL, regular_pay REAL, overtime_pay REAL, other_pay REAL)''')
    # Insert data into table
    for year in range(start_year, end_year + 1):
        if year in DATA_LOADED:
            df = DATA_LOADED[year]
        else:
            print(f"Loading data for {year}...")
            df = load_data_for_year(year)
        df = normalize_df_for_db(df)
        df.to_sql('salaries', conn, if_exists='append', index=False)
        print(f"Inserted {len(df)} records for {year} into the database.")
        conn.commit()

In [ ]:
DB_FILE = 'data/uc_salaries_test.db'
DATA_LOADED = {}
conn = sqlite3.connect(DB_FILE)
cursor = conn.cursor()
# Load data into SQLite database
load_sqlite_db(conn, start_year=2010, end_year=2023)

Loading data for 2010...
Loaded 252540 records for 2010
Inserted 252540 records for 2010 into the database.
Loading data for 2011...
Loaded 259043 records for 2011
Inserted 259043 records for 2011 into the database.
Loading data for 2012...
Loaded 262416 records for 2012
Inserted 262416 records for 2012 into the database.
Loading data for 2013...
Loaded 268442 records for 2013
Inserted 268442 records for 2013 into the database.
Loading data for 2014...
Loaded 275257 records for 2014
Inserted 275257 records for 2014 into the database.
Loading data for 2015...
Loaded 281541 records for 2015
Inserted 281541 records for 2015 into the database.
Loading data for 2016...

In [38]:
df2010 = DATA_LOADED[2010]

In [39]:
df2010.head()

,id,Year,Location,First Name,Last Name,Title,Gross Pay,Regular Pay,Overtime Pay,Other Pay
0,1,2010,Santa Cruz,*****,*****,ASSISTANT PROFESSOR-ACAD YR,74511.10,69999.96,0.0,4511.14
1,2,2010,Berkeley,***********,***********,GRAD STDNT RES-FULL FEE REM,5369.42,5369.42,0.0,0.00
2,3,2010,Berkeley,***********,***********,TEACHING ASSISTANT - GSHIP,4802.00,4802.00,0.0,0.00
3,4,2010,Berkeley,***********,***********,GRAD STDNT RES- NO REMISSION,3409.01,3409.01,0.0,0.00
4,5,2010,Berkeley,***********,***********,GRAD STDNT RES-FULL FEE REM,11673.90,11673.90,0.0,0.00

In [34]:
# Cleanup the test salaries table
# c.execute('DROP TABLE salaries;')
# c.execute('ALTER TABLE test_salaries RENAME TO salaries;')
# c.fetchall()

OperationalError: database is locked

In [26]:
# Write db to a file
conn.commit()
conn.close()

In [25]:
c.execute('SELECT COUNT(*), year FROM salaries GROUP BY year;')
c.fetchall()

[(268442, 2013),
 (275257, 2014),
 (281541, 2015),
 (291141, 2016),
 (298070, 2017),
 (307858, 2018),
 (315668, 2019),
 (296019, 2020),
 (305565, 2021),
 (331143, 2022),
 (343478, 2023)]

In [21]:
c.execute('PRAGMA table_info(test_salaries);')
c.fetchall()

[(0, 'index', 'INTEGER', 0, None, 0),
 (1, 'id', 'REAL', 0, None, 0),
 (2, 'Year', 'REAL', 0, None, 0),
 (3, 'Location', 'TEXT', 0, None, 0),
 (4, 'First Name', 'TEXT', 0, None, 0),
 (5, 'Last Name', 'TEXT', 0, None, 0),
 (6, 'Title', 'TEXT', 0, None, 0),
 (7, 'Gross Pay', 'REAL', 0, None, 0),
 (8, 'Regular Pay', 'REAL', 0, None, 0),
 (9, 'Overtime Pay', 'REAL', 0, None, 0),
 (10, 'Other Pay', 'REAL', 0, None, 0)]

## Title Codes Mapping Notes

* Need to map `titles` across years.
* Do different payroll titles keep the same internal UC titlecode?
* Want a list of all titles per year, with a way to map one title across years.

### Schema?

* title
* year
* uc_titlecode
* uc_category -- see what UC provides
* category -- from the google sheet


## Timeseries Analysis

* Need a way to link people across years (Name, cleaned title, campus)